#!/bin/sh
# Sets screen color temperature and brightness depending on time

hour=$(date +%H)
if [ "$hour" -ge 16 ] || [ "$hour" -le 9 ]; then
    if [ "$hour" -ge 16 ]; then
        delta=$(($hour-16))
    else
        delta=$((9-$hour))
    fi
    sct $((10000-$delta*1000)) $(bc --mathlib <<< "(1-$delta/20)")
else
    sct
fi
